### ISSUE TITLE
PA Review: Search

### ISSUE THREAD

**Issue by jyschwrtz** [jyschwrtz/Pied-Piper#9]
- [x] Search returns accurate results
 - [x] Adequate seeding
 - [x] Styling

**Comment by jyschwrtz** [comment]
I still plan to add more data and styling, but thought it may be good to have you take a look at this as well.

**Comment by s-pangburn** [comment]
- [x] Needs a little more padding between the search bar and the "Songs" header
- [ ] The bullet points under the "Users" header should either be further to the right or not there at all.

However, neither of these would ruin your project. What's here is more than adequate, so I'll mark this feature as complete 👍
